# @package _global_

# IQN is currently not compatible with QV or QVMAX

#opt:
#  name: adam
#  eps: 0.0003125
#  lr: 0.00005

agent:
  iqn: 1
  munch_q: 1
  policy:
    tau: 0.03
    l0: -1
    alpha: 0.9
    num_tau: 8
    num_policy_samples: 32
