# @package _global_

opt:
  lr: 0.00025

learner:
  # env wrappers params
  frame_stack: 4
  frameskip: 4
  grayscale: 1
  # training params
  steps_per_batch: 4
  batch_size: 32
  # size params
  warm_start_size: 50000
  

buffer:
  buffer_size: 1000000

agent:
  # learn alg params
  eps_start: 0.1
  # target net params
  target_net_hard_steps: 10000
  target_net_polyak_val: 0.99
  target_net_use_polyak: 0
  policy:   
    gamma: 0.99
    net:
        width: 512
