"""1-Step World Model and AlphaZero-style Update Rule."""

from typing import Any, cast

import torch
import torch.nn.functional as F  # noqa: N812
from torch import nn, optim

from roboro.core.types import Batch
from roboro.updates.base import BaseUpdate, UpdateResult


class WorldModelUpdate(BaseUpdate):
    """Trains a 1-step dynamics model and AlphaZero-style actor-critic.

    This update performs two distinct tasks simultaneously:
    1. Trains the `dynamics_net` to predict the true next state and reward from the
       ReplayBuffer.
    2. Trains the `policy_net` and `value_net` to predict the targets generated by
       MCTS (visit counts and root value estimates), which are retrieved from the
       `batch.extras` dictionary.

    Args:
        dynamics_net: a module taking ``(state, action)`` and returning
            ``(next_state, reward)``.
        value_net: a module taking ``(state)`` and returning a scalar value.
        policy_net: a module taking ``(state)`` and returning unnormalized action logits.
        lr: learning rate for all three networks.
        max_grad_norm: global gradient clipping norm.
    """

    def __init__(
        self,
        dynamics_net: nn.Module,
        value_net: nn.Module,
        policy_net: nn.Module,
        gamma: float = 0.99,
        lr: float = 1e-3,
        max_grad_norm: float = 10.0,
    ) -> None:
        self.dynamics_net = dynamics_net
        self.value_net = value_net
        self.policy_net = policy_net
        self.gamma = gamma
        self.max_grad_norm = max_grad_norm

        # We can optimize all networks together since their losses are summed.
        # Alternatively, we could have separate optimizers if they require different LRs.
        params = (
            list(dynamics_net.parameters())
            + list(value_net.parameters())
            + list(policy_net.parameters())
        )
        self.optimizer = optim.Adam(params, lr=lr)

    def update(self, batch: Batch, step: int) -> UpdateResult:
        """Run one gradient step for the world model and actor-critic."""

        # Retrieve the MCTS targets that were stored by the MCTSActor during the environment loop.
        if "mcts_policy" not in batch.extras or "mcts_value" not in batch.extras:
            raise ValueError(
                "WorldModelUpdate requires 'mcts_policy' and 'mcts_value' in batch.extras. "
                "Ensure you are using MCTSActor and passing info dicts to the replay buffer."
            )

        mcts_policy_target = batch.extras["mcts_policy"].to(batch.obs.device)

        # ── 1. Train the Dynamics Model (Reality Prediction) ────────────────

        # The dynamics model takes the current observation and the action that was taken,
        # and predicts the resulting next observation, reward, and done signal.
        pred_next_obs, pred_reward_logits, pred_done_logits = self.dynamics_net(
            batch.obs, batch.actions, return_logits=True
        )

        # Squeeze reward targets to match prediction shape if necessary
        true_rewards = batch.rewards
        if true_rewards.ndim == 1:
            true_rewards = true_rewards.unsqueeze(1)

        reward_targets = cast(Any, self.dynamics_net).support.to_categorical(true_rewards)

        # Squeeze done targets
        true_dones = batch.dones.float()
        if true_dones.ndim == 1 and pred_done_logits.ndim == 2:
            true_dones = true_dones.unsqueeze(1)
        elif true_dones.ndim == 2 and pred_done_logits.ndim == 1:
            pred_done_logits = pred_done_logits.unsqueeze(1)

        loss_transition = F.mse_loss(pred_next_obs, batch.next_obs)
        loss_reward = F.cross_entropy(pred_reward_logits, reward_targets)

        # Binary cross entropy for done prediction (using logits)
        loss_done = F.binary_cross_entropy_with_logits(pred_done_logits, true_dones)

        dynamics_loss = loss_transition + loss_reward + loss_done

        # ── 2. Train the Actor-Critic (MCTS Target Prediction) ─────────────

        # The policy net predicts unnormalized logits over the discrete action space.
        # We train it to match the improved policy distribution (visit counts) from MCTS.
        pred_logits = self.policy_net(batch.obs)
        if pred_logits.shape != mcts_policy_target.shape or mcts_policy_target.dtype not in (
            torch.float16,
            torch.float32,
            torch.float64,
        ):
            print(
                f"SHAPES: logits={pred_logits.shape}, target={mcts_policy_target.shape}, DTYPE={mcts_policy_target.dtype}"
            )

        policy_loss = F.cross_entropy(pred_logits, mcts_policy_target)

        # The value net predicts the expected return from this state.
        # We use a 1-step TD target to ground the value network to real rewards and done signals.
        # Without this, the value network would only train against MCTS values (which are
        # based on the dynamics model), and since our dynamics model doesn't perfectly predict
        # every future, the values would diverge and hallucinate infinite rewards.
        pred_value_logits = self.value_net(batch.obs, return_logits=True)

        with torch.no_grad():
            next_value = self.value_net(batch.next_obs)
            if next_value.ndim == 2:
                next_value = next_value.squeeze(-1)

            # Ensure rewards and dones are 1D for TD target
            rewards_1d = batch.rewards.squeeze(-1) if batch.rewards.ndim == 2 else batch.rewards
            dones_1d = batch.dones.squeeze(-1) if batch.dones.ndim == 2 else batch.dones

            td_target = rewards_1d + self.gamma * next_value * (~dones_1d).float()
            categorical_td_target = cast(Any, self.value_net).support.to_categorical(
                td_target.unsqueeze(-1)
            )

        value_loss = F.cross_entropy(pred_value_logits, categorical_td_target)

        # ── 3. Combined Gradient Step ───────────────────────────────────────

        # Total loss is simply the sum. In a more advanced implementation (like MuZero),
        # these losses are often scaled by coefficients.
        total_loss = dynamics_loss + policy_loss + value_loss

        if torch.isnan(total_loss):
            print("\nNaN Loss Detected!")
            print(f"dynamics_loss={dynamics_loss.item()}")
            print(f"policy_loss={policy_loss.item()}")
            print(f"value_loss={value_loss.item()}")

        self.optimizer.zero_grad()
        total_loss.backward()
        grad_norm = nn.utils.clip_grad_norm_(
            list(self.dynamics_net.parameters())
            + list(self.value_net.parameters())
            + list(self.policy_net.parameters()),
            self.max_grad_norm,
        )
        self.optimizer.step()

        return UpdateResult(
            loss=total_loss.item(),
            metrics={
                "loss/dynamics_transition": loss_transition.item(),
                "loss/dynamics_reward": loss_reward.item(),
                "loss/dynamics_done": loss_done.item(),
                "loss/policy": policy_loss.item(),
                "loss/value": value_loss.item(),
                "grad_norm": float(grad_norm),
            },
        )
